// examples/figma/output/minimal-react-plugin-ts/components/Input.tsx
import React from 'react'

const Input = ({ value = '', type = 'text', showIcon = false, onChange }) => {
	const containerStyle = {
		display: 'flex',
		alignItems: 'center',
		gap: '4px',
		padding: '4px 8px',
		border: '1px solid var(--figma-color-border)',
		borderRadius: '4px',
		backgroundColor: 'var(--figma-color-bg)',
		color: 'var(--figma-color-text)',
		fontSize: '12px',
		fontFamily: 'Inter, sans-serif',
	}

	const inputStyle = {
		border: 'none',
		outline: 'none',
		backgroundColor: 'transparent',
		color: 'inherit',
		fontSize: 'inherit',
		fontFamily: 'inherit',
		width: '100%',
		minWidth: '0',
	}

	const iconStyle = {
		color: 'var(--figma-color-text-secondary)',
		fontSize: '10px',
		fontWeight: 'bold',
	}

	const handleInputChange = (event) => {
		if (onChange) {
			onChange(event.target.value)
		}
	}

	return (
		<div style={containerStyle} data-non-interactive="true">
			<div style={{ display: 'contents' }}>
				<label
					data-tooltip-type="text"
					data-tooltip="X-position"
					aria-label="X-position"
					data-onboarding-key="scrubbable-control-x-position"
					data-temporary-fpl-no-drag=""
					style={{ display: 'flex', alignItems: 'center', gap: '4px', width: '100%' }}
				>
					{showIcon && <span style={iconStyle}>X</span>}
					<input
						type={type}
						value={value}
						onChange={handleInputChange}
						spellCheck={false}
						dir="auto"
						style={inputStyle}
					/>
				</label>
			</div>
		</div>
	)
}

export default Input

// examples/figma/output/minimal-svelte-plugin-ts/components/Input.svelte
// Source: templates/frameworks/svelte/components/Input.svelte
<script lang="ts">
	let { value = $bindable(''), type = 'text', showIcon } = $props()
</script>

<div class="Input" data-non-interactive="true">
	<div class="displayContents">
		<label
			data-tooltip-type="text"
			data-tooltip="X-position"
			aria-label="X-position"
			data-onboarding-key="scrubbable-control-x-position"
			data-temporary-fpl-no-drag=""
		>
			{#if showIcon}
				<span class="icon"><i18n-text>X</i18n-text></span>
			{/if}
			<input {type} spellcheck="false" dir="auto" bind:value /></label
		>
	</div>
</div>

<style>
	.displayContents {
		display: contents;
	}
	.icon {
		display: flex;
		align-items: center;
		justify-content: center;
		height: var(--spacer-4);
		width: var(--spacer-4);
		flex: 0 0 var(--spacer-4);
		line-height: var(--spacer-4);
		stroke: unset;

		color: var(--figma-color-icon-secondary);
		margin-left: -1px;
		vertical-align: top;
		text-transform: none !important;
		-moz-osx-font-smoothing: grayscale;
		-webkit-font-smoothing: antialiased;
		text-align: center;
		pointer-events: none;
		line-height: var(--spacer-4);
		letter-spacing: inherit;
		text-decoration: none;
		font-weight: 400;
		margin-right: -8px;
	}
	label {
		margin: 1px 0;
		display: flex;
		background-color: var(--figma-color-bg-secondary);
		border: 1px solid transparent;
		height: var(--spacer-4);
		border-radius: var(--radius-medium);
		align-items: center;
	}

	label:hover {
		border-color: var(--figma-color-border);
	}

	label:focus-within {
		border-color: var(--figma-color-border-selected);
		border-width: 1px;
	}

	input {
		height: var(--spacer-4);
		display: flex;
		margin: 0;
		padding: 0 7px;
		border: 1px solid transparent;
		border-left: 0;
		border-right: 0;
		background-clip: padding-box;
		margin-left: 0;
		width: 100%;
	}

	input:focus-visible {
		outline: unset;
	}

	input[type='number']::-webkit-inner-spin-button,
	input[type='number']::-webkit-outer-spin-button {
		-webkit-appearance: none;
		margin: 0;
	}

	/* For Firefox */
	input[type='number'] {
		-moz-appearance: textfield;
	}
</style>
