// examples/figma/output/basic-react-plugin/src/ui/App.tsx
import { useState, useEffect } from 'react'
import reactLogo from './assets/react.svg'
import Icon from './components/Icon'
import Input from './components/Input'
import Button from './components/Button'
import './App.css' // Import CSS for styles

const App = () => {
	const [rectCount, setRectCount] = useState<number>(5)
	const [nodeCount, setNodeCount] = useState<number>(0)

	const createRectangles = (count) => {
		window.parent.postMessage(
			{
				pluginMessage: {
					type: 'CREATE_RECTANGLES',
					count,
				},
			},
			'*',
		)
	}

	useEffect(() => {
		const handleMessage = (event) => {
			const message = event.data.pluginMessage
			if (message?.type === 'POST_NODE_COUNT') {
				setNodeCount(message.count)
			}
		}

		window.addEventListener('message', handleMessage)
		return () => {
			window.removeEventListener('message', handleMessage)
		}
	}, [])

	return (
		<div className="container">
			<div className="banner">
				<Icon svg="plugma" size={38} />
				<Icon svg="plus" size={24} />
				<img src={reactLogo} width="44" height="44" alt="Svelte logo" />
			</div>

			<div className="field create-rectangles">
				<Input type="number" value={rectCount} onChange={(e) => setRectCount(Number(e.target.value))} />
				<Button onClick={() => createRectangles(rectCount)}>Create Rectangles</Button>
			</div>
			<div className="field node-count">
				<span>{nodeCount} nodes selected</span>
			</div>
		</div>
	)
}

export default App

// examples/figma/output/basic-svelte-plugin/src/ui/App.svelte
<script>
	import svelteLogo from './assets/svelte.svg'
	import Icon from './components/Icon.svelte'
	import Input from './components/Input.svelte'
	import Button from './components/Button.svelte'
	function createRectangles(count) {
		parent.postMessage(
			{
				pluginMessage: {
					type: 'CREATE_RECTANGLES',
					count,
				},
			},
			'*',
		)
	}
	let rectCount = $state(5)
	let nodeCount = $state(0)
	window.onmessage = (event) => {
		let message = event.data.pluginMessage
		if (message.type === 'POST_NODE_COUNT') {
			nodeCount = message.count
		}
	}
</script>

<div class="container">
	<div class="banner">
		<Icon svg="plugma" size={38} />

		<Icon svg="plus" size={24} />

		<img src={svelteLogo} width="44" height="44" alt="Svelte logo" />
	</div>

	<div class="field create-rectangles">
		<Input type="number" bind:value={rectCount}></Input>
		<Button onclick={() => createRectangles(rectCount)}>Create Rectangles</Button>
	</div>
	<div class="field node-count">
		<span>{nodeCount} nodes selected</span>
	</div>
</div>

<style>
	.container {
		display: flex;
		align-items: center;
		justify-content: center;
		height: 100%;
		width: 100%;
		flex-direction: column;
	}
	.banner {
		display: flex;
		align-items: center;
		gap: 18px;
		margin-bottom: 16px;
	}

	.node-count {
		font-size: 11px;
	}

	.field {
		display: flex;
		gap: var(--spacer-2);
		height: var(--spacer-5);
		align-items: center;
	}

	.create-rectangles :global(.Input) {
		width: 40px;
	}
</style>
